---
- name: Check if file exists
  ansible.builtin.stat:
    path: /etc/modules-load.d/11-k8s.conf
  register: file_status

- name: Check file availability
  when: not file_status.stat.exists
  block:
    - name: Create the file if it doesn't exist
      ansible.builtin.file:
        path: /etc/modules-load.d/11-k8s.conf
        state: touch
        mode: '0755'

    - name: Add br_netfilter module to modules-load.d
      ansible.builtin.copy:
        content: "br_netfilter\n"
        dest: /etc/modules-load.d/11-k8s.conf
        mode: '0755'

    - name: Load Kernel Modules
      ansible.builtin.command: /sbin/modprobe -a br_netfilter
      changed_when: true

    - name: Configure Kernel Parameters
      ansible.posix.sysctl:
        sysctl_file: /etc/sysctl.d/11-k8s.conf
        name: "{{ item }}"
        value: 1
      loop:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward

    - name: Reload sysctl
      ansible.builtin.command: sysctl --system
      changed_when: false
