---
- name: Deploy common packages
  hosts: master
  become: true
  roles:
    - commons
    - configure-kernel
    - containerd

# ====== Setup & Configure Master Node ==============
- name: Setup Master
  hosts: master
  become: true
  roles:
    - cluster-setup
  tags: master_check
